language: node_js
node_js:
  - "8"
script:
  - npm test
  - npm install apify-cli -g
  - bash apify login --token $APIFY_TOKEN
deploy:
  # deploy develop to the staging environment
  - provider: script
    script: bash apify push --build-tag beta
    on:
      branch: develop
  # deploy master to production
  - provider: script
    script: bash apify push --build-tag latest
    on:
      branch: master
